apiVersion: v1
kind: ConfigMap

metadata:
  name: order-service-config

data:
  APP_ENVIRONMENT: {{ .Values.app.environment | quote }}
  ORDER_TIMEOUT_SECONDS: {{ .Values.app.orderTimeoutSeconds | quote }}