{{- if .Values.config.enabled }}

apiVersion: v1
kind: ConfigMap

metadata:
  name: order-service-config

data:
  APP_ENVIRONMENT: {{ .Values.config.environment | quote }}
  ORDER_TIMEOUT_SECONDS: {{ .Values.config.orderTimeoutSeconds | default "30" | quote }}

{{- end }}