apiVersion: v1
kind: Service

metadata:
  name: order-service
  labels:
    app: order-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: order-service

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP